// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package kdb

import (
	"database/sql"
)

type Principal struct {
	ID          int64        `db:"id"`
	PrimaryName string       `db:"primary_name"`
	Instance    string       `db:"instance"`
	Realm       string       `db:"realm"`
	KeyBytes    []byte       `db:"key_bytes"`
	Kvno        int64        `db:"kvno"`
	CreatedAt   sql.NullTime `db:"created_at"`
}
