// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package kdb

import (
	"context"
)

type Querier interface {
	//CreatePrincipal
	//
	//  INSERT INTO principals (
	//      primary_name,
	//      instance,
	//      realm,
	//      key_bytes,
	//      kvno
	//  ) VALUES (
	//      ?, ?, ?, ?, ?
	//  )
	//  RETURNING id, primary_name, instance, realm, key_bytes, kvno, created_at
	CreatePrincipal(ctx context.Context, db DBTX, arg CreatePrincipalParams) (Principal, error)
	//GetPrincipal
	//
	//  SELECT key_bytes, kvno
	//  FROM principals
	//  WHERE primary_name = ? AND instance = ? AND realm = ?
	//  LIMIT 1
	GetPrincipal(ctx context.Context, db DBTX, arg GetPrincipalParams) (GetPrincipalRow, error)
	//ListPrincipals
	//
	//  SELECT primary_name, instance, realm
	//  FROM principals
	//  ORDER BY primary_name, instance
	ListPrincipals(ctx context.Context, db DBTX) ([]ListPrincipalsRow, error)
}

var _ Querier = (*Queries)(nil)
